#!/usr/bin/env python3

# ubpkg
#  - userbyte package manager

import sys, os

version = 3

command = sys.argv[1]
package = sys.argv[2]

if command in ['install', 'i']:
    os.system(f'sudo pacman -Sy {package}')
elif command == ['uninstall', 'u', 'r']:
    os.system(f'sudo pacman -Rns {package}')