#!/usr/bin/env python3

# ubpkg
#  - userbyte package manager

import sys, os

version = 4

command = sys.argv[1]
package = ' '.join(sys.argv[2:])

if command in ['install', 'i']:
    os.system(f'sudo pacman -S {package}')
elif command in ['uninstall', 'remove', 'rm', 'r']:
    os.system(f'sudo pacman -Rns {package}')
elif command in ['update', 'upgrade', 'u']:
    os.system(f'sudo pacman -Syu')